ALTER TABLE students ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE students ADD COLUMN is_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE students ADD COLUMN otp_requests_today INT NOT NULL DEFAULT 0;

ALTER TABLE tpos ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE tpos ADD COLUMN is_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tpos ADD COLUMN otp_requests_today INT NOT NULL DEFAULT 0;

ALTER TABLE otp_verifications ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

